### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TheSecureTux** [Rolix44/Kubestroyer#9]
Hi! So far all working nicely until, when scanning a node which had port 8500 open :
```
 ~/hack/Kubestroyer/ [master] ./Kubestroyer -t X.X.X.X  --node-scan

 _   __      _               _
| | / /     | |             | |
| |/ / _   _| |__   ___  ___| |_ _ __ ___  _   _  ___ _ __
|    \| | | | '_ \ / _ \/ __| __| '__/ _ \| | | |/ _ \ '__| v0.2
| |\  \ |_| | |_) |  __/\__ \ |_| | | (_) | |_| |  __/ |
\_| \_/\__,_|_.__/ \___||___/\__|_|  \___/ \__, |\___|_|
                                            __/ |
                                           |___/
			                        By Rolix

--------------------------------------------------------

Starting port scan for 'X.X.X.X'...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x124ef4e]

goroutine 1 [running]:
github.com/Rolix44/Kubestroyer/pkg.nodeport_scan({0x7ff7bfeff9f1, 0xe}, 0x7963)
	/Users/jordi/hack/Kubestroyer/pkg/scanning.go:20 +0x6e
github.com/Rolix44/Kubestroyer/pkg.check_ports({0x7ff7bfeff9f1, 0xe})
	/Users/jordi/hack/Kubestroyer/pkg/scanning.go:44 +0x454
github.com/Rolix44/Kubestroyer/pkg.Execute()
	/Users/jordi/hack/Kubestroyer/pkg/cmd.go:35 +0x345
main.main()
	/Users/jordi/hack/Kubestroyer/cmd/kubestroyer/main.go:17 +0x125
```

Running on 
![image](https://github.com/Rolix44/Kubestroyer/assets/24679987/57d07ca2-3c80-49e7-ae59-cf8a051edd5e)

` ~/hack/Kubestroyer/ [master] go version
go version go1.20.5 darwin/amd64`

**Comment by Rolix44** [comment]
Hello there, sorry for the late response. Seems weird to me as the tool is not scanning the port 8500.

I'm not on mac and for the moment impossible to trigger this behavior on my environment.

Can you retry with an other node  ?
